# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Ripu Sudan Chauhan
title: Java Full Stack Developer & MEAN Stack Developer
email: ripu.cmos@gmail.com
website: www.ripusudan.github.io

# Social links
#twitter_username: facespics
github_username:  ripusudan
# dribbble_username: jekyll
facebook_username: ripusudan.chauhan
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: jameswgrant
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Ripu Sudan Chauhan and I am a Full stack java developer and MEAN stack Developer. 
  I majorely worked on all technologies like 

  I am most skilled in: <mark>JAVA</mark> and <mark>UI Technologies</mark>

Projects Section
projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
