# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Ripu Sudan Chauhan
title: Java Full Stack Developer & Node JS Developer
email: ripu.cmos@gmail.com
website: www.ripusudan.github.io

# Social links
#twitter_username: facespics
github_username:  ripusudan
# dribbble_username: jekyll
facebook_username: ripusudan.chauhan
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: ripu-sudan-chauhan
medium_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  >Hay, This is Ripu Sudan Chauhan ,who love coding and solving problems.I makes computers intelligent by giving them Algorithms. I am a Full stack java developer.
  Now a days i am working on NODE JS => Hence i knows trending JS => JS can make mobile app(i was excited!!) Learned REACT JS.
  I have worked on both front end and backend technologies as shown below.
  

  <mark>JAVA(8)</mark> <mark>ANGULAR(JS)</mark> <mark>SPRING(REST+BOOT+BTACH)</mark> <mark>HIBERNATE</mark> <mark>JSP</mark>
  <mark>SERVLET</mark> <mark>DESIGN PATTERN</mark> <mark>MULTI THREADING</mark> <mark>COLLECTIONS</mark> 
  <mark>HTML</mark> <mark>CSS</mark> <mark>BOOTSTRAP</mark>
  <BR><mark>NODEJS</mark> <mark>JAVASCRIPT(+ES6)</mark> <mark>EXPRESS JS</mark> <mark>REACT NATIVE</mark>  <mark>JQUERY</mark> <mark>EXTJS</mark> 
  <BR><mark>JUNIT</mark> <mark>MOCKITO</mark> <mark>SELENIUM</mark> <mark>CHAI</mark> <mark>MOCHA</mark>
  <BR><mark>SHELL SCRIPTING</mark> <mark>LINUX SCRIPTING</mark> <mark>LINUX</mark>
  <BR><mark>ORACLE</mark> <mark>DB2</mark> <mark>MONGODB</mark>
  <BR><mark>APACHE TOMCAT</mark>
  <BR><mark>GRADLE</mark> <mark>MAVEN</mark> <mark>ANT</mark>
  <BR><mark>GIT</mark> <mark>SVN</mark> 
  <BR><mark>ZABBIX</mark> <mark>REDIS</mark> 
 
  
 

#Projects Section
#projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Drawing
   - Acquiring Knowledge 
   - Playing with my kids

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
