# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Ripu Sudan Chauhan
title: Java Full Stack Developer & MEAN Stack Developer
email: ripu.cmos@gmail.com
website: www.ripusudan.github.io

# Social links
#twitter_username: facespics
github_username:  ripusudan
# dribbble_username: jekyll
facebook_username: ripusudan.chauhan
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: jameswgrant
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, My name is Ripu Sudan Chauhan and I am a Full stack java developer and MEAN stack Developer. 
  I mainly worked on both front end and backend technologies as shown below.
  

  I am most skilled in: <mark>JAVA(8)</mark> <mark>ANGULAR(JS)</mark> <mark>SPRING</mark> <mark>HIBERNATE</mark> <mark>JSP</mark>
  <mark>SERVLET</mark>
  <mark>HTML</mark> <mark>CSS</mark> <mark>BOOTSTRAP</mark>
  <BR><mark>JQUERY</mark> <mark>EXTJS</mark> <mark>JAVASCRIPT</mark> <mark>NODEJS</mark>
  <BR><mark>JUNIT</mark> <mark>MOCKITO</mark> <mark>SELENIUM</mark>
  <BR><mark>SHELL SCRIPTING</mark> <mark>LINUX SCRIPTING</mark> <mark>LINUX</mark>
  <BR><mark>ORACLE</mark> <mark>DB2</mark> <mark>MONGODB</mark>
  <BR><mark>APACHE TOMCAT</mark>
  <BR><mark>GRADLE</mark> <mark>MAVEN</mark> <mark>ANT</mark>
 
  
 

#Projects Section
#projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Drawing
   - Acquiring Knowledge 
   - Playing with my kids

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
